from enum import Enum

class Payoffs(Enum):
    WON_GAME = 20
    LOST_GAME = -10
    GAINED_VALID_OPTIONS_PER_CARD = 1
    LOST_VALID_OPTIONS_PER_CARD = -1
    CAUSED_NEXT_PLAYER_TO_WIN = -5
    USED_WILD_CARD_WHEN_HAD_OTHER_VALID_OPTIONS = -5
    OPTIMIZED_WILD_CARD = 5
    USED_DRAW_2_CARD = -3
    USED_SKIP_OR_REVERSE_CARD = 2
    USED_NORMAL_CARD = 1